local colorbuddy = require("colorbuddy")
local Group = colorbuddy.Group
local colors = colorbuddy.colors
local styles = colorbuddy.styles

-- Editor highlights
Group.new("ColorColumn", colors.none, colors.bg.subtle)
Group.new("Conceal", colors.fg.subtle)
Group.new("Cursor", colors.bg.default, colors.fg.muted)
Group.new("lCursor", colors.bg.default, colors.fg.muted)
Group.new("CursorIM", colors.bg.default, colors.fg.muted)
Group.new("CursorColumn", colors.none, colors.bg.subtle)
Group.new("CursorLine", colors.none, colors.bg.subtle)
Group.new("Directory", colors.syntax.func)
Group.new("DiffAdd", colors.none, colors.git.add)
Group.new("DiffChange", colors.none, colors.git.changed)
Group.new("DiffDelete", colors.none, colors.git.removed)
Group.new("DiffText", colors.none, colors.attention.muted)
Group.new("EndOfBuffer", colors.bg.default)
Group.new("ErrorMsg", colors.diag.error)
Group.new("VertSplit", colors.border.subtle)
Group.new("WinSeparator", colors.border.subtle)
Group.new("Folded", colors.fg.muted, colors.bg.subtle)
Group.new("FoldColumn", colors.fg.muted)
Group.new("SignColumn", colors.fg.muted)
Group.new("SignColumnSB", colors.fg.muted)
Group.new("Substitute", colors.bg.default, colors.diag.error)
Group.new("LineNr", colors.fg.subtle)
Group.new("CursorLineNr", colors.fg.default)
Group.new("MatchParen", colors.fg.default, colors.accent.muted, styles.bold)
Group.new("ModeMsg", colors.diag.warn, colors.none, styles.bold)
Group.new("MoreMsg", colors.diag.info, colors.none, styles.bold)
Group.new("NonText", colors.fg.muted)
Group.new("Normal", colors.fg.default, colors.bg.default)
Group.new("NormalNC", colors.fg.default, colors.bg.default)
Group.new("NormalFloat", colors.fg.default, colors.bg.inset)
Group.new("FloatBorder", colors.border.default)
Group.new("Pmenu", colors.fg.default, colors.bg.inset)
Group.new("PmenuSel", colors.none, colors.accent.subtle)
Group.new("PmenuSbar", colors.none, colors.bg.inset)
Group.new("PmenuThumb", colors.none, colors.bg.subtle)
Group.new("Question", colors.diag.info, colors.none, styles.bold)
Group.new("QuickFixLine", colors.none, colors.bg.subtle)
Group.new("Search", colors.none, colors.attention.subtle)
Group.new("IncSearch", colors.bg.default, colors.attention.fg)
Group.new("CurSearch", colors.bg.default, colors.attention.fg)
Group.new("SpecialKey", colors.fg.muted)
Group.new("SpellBad", colors.diag.error, colors.none, styles.undercurl)
Group.new("SpellCap", colors.diag.warn, colors.none, styles.undercurl)
Group.new("SpellLocal", colors.diag.info, colors.none, styles.undercurl)
Group.new("SpellRare", colors.diag.info, colors.none, styles.undercurl)
Group.new("TabLine", colors.fg.muted, colors.bg.subtle)
Group.new("TabLineFill", colors.none, colors.bg.inset)
Group.new("TabLineSel", colors.bg.default, colors.fg.muted)
Group.new("Title", colors.syntax.constant, colors.none, styles.bold)
Group.new("Visual", colors.none, colors.accent.subtle)
Group.new("VisualNOS", colors.none, colors.accent.subtle)
Group.new("WarningMsg", colors.diag.warn)
Group.new("Whitespace", colors.bg.subtle)
Group.new("WildMenu", colors.fg.default, colors.bg.inset)
Group.new("WinBar", colors.fg.muted, colors.bg.default, styles.bold)
Group.new("WinBarNC", colors.fg.muted, colors.bg.default, styles.bold)

-- Additional groups
Group.new("StatusLine", colors.fg.default, colors.bg.subtle)
Group.new("StatusLineNC", colors.fg.muted, colors.bg.subtle)
